### ISSUE TITLE
fromString function

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-integers#11]
I was thinking a `fromString :: String -> Maybe Int` type function would be handy. There's a `readInt` in `purescript-globals`, and an instance in `purescript-foreign` of course, but it would be nice to have a version which is safe for `Int32` or whatever the current platform's precision is.

**Comment by paf31** [comment]
:+1:

**Comment by garyb** [comment]
Done in 072fd390baab8e9c7b84e966bbb77adea3894448
