### ISSUE TITLE
fromNumber behaviour

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-integers#12]
After implementing `fromString` it got me thinking - should `fromNumber` return a `Maybe` and fail when given an out-of-range integer or non-integer Number?

**Comment by jdegoes** [comment]
Once we have literals, I'd say yes, but before then, I wouldn't think so, since it will make any case involving literals pretty nasty. But still, I hope if you call `fromNumber` on something that has a fractional component, it's truncated, and if you call it on something too big or too large, it's clamped.

**Comment by garyb** [comment]
Yeah, this is for when we have literals.

I was thinking we'd want the `Maybe` behaviour because otherwise there is no way of knowing that something did happen to your number, without casting it back using `toNumber` and seeing if it matches the input. Making `fromNumber` only work with integer `Number`s also promotes the use of `round`, `floor`, or `ceil` then too, to ensure you explicitly get the desired behaviour when operating on something that may have a fractional component.

It could definitely be annoying though, it's a fine line. I'm not sure how frequently `fromNumber` will be of use when we have literals.

**Comment by jdegoes** [comment]
:+1: `Maybe` return value should be used and it needs to be an integer that fits inside the range of integers, else you get back `Nothing`. And you're right, this will promote explicit rounding / clamping behavior, which is a good thing.
