### ISSUE TITLE
Provide fromNumber which floors

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-integers#13]
The old version was still useful, I think.

**Comment by jdegoes** [comment]
Isn't it better to call `Math floor` so the rounding mode is made explicit? I'd prefer to know when I look at the code how, e.g., -2278.4323 will be translated into an integer.

**Comment by garyb** [comment]
Yeah, the old version didn't strictly speaking `floor` either, it just removed the decimal places.

**Comment by hdgarrood** [comment]
Perhaps it would be useful to add versions of `floor`, `ceil`, and `round` to this library then? I guess `Math.floor` probably should keep the type `Number -> Number`, so that it can be used with numbers outside the Int range.

**Comment by jdegoes** [comment]
> Yeah, the old version didn't strictly speaking floor either, it just removed the decimal places.

i.e. `chomp`.

**Comment by sharkdp** [comment]
This is probably resolved?

**Comment by hdgarrood** [comment]
Yep, resolved by #14.
