### ISSUE TITLE
fromNumber range

### ISSUE THREAD

**Issue by passy** [purescript/purescript-integers#15]
Hey, I saw #12 but it left me a bit puzzled.

While upgrading to PureScript 0.7 a test for my JSON started to fail because a timestamp could no longer be parsed as Integer. The problem is that `1429969259654` cannot be converted from `Number` to `Int` given the current logic, since it's larger than (2^31 - 1).

I was under the impression that everything below 2^53 is considered to be safe or is this specifically to allow bit operations?

Either way, it might be useful to document the behavior. :)

**Comment by passy** [comment]
Actually, on second thought this is pretty clear. If the library provides bit operations, those should safely work within the given range and I'm not even sure if the ECMAScript standard specifies the range in which you can apply those. Sorry for the noise.

**Comment by garyb** [comment]
The way we ensure numbers stay as integers is by using `|0` in JS, so that's why we have this 32-bit size `Int` - that does appear to be the range, but yeah I don't know if it's in the spec.

**Comment by legrostdg** [comment]
I just encountered this, trying to debug an issue in `purescript-argonaut-generic-codecs`. This package uses `purescript-integers` to convert Json to Int. This `fromNumber 2311048878.0 == Nothing` is quite unfortunate, especially coming from Haskell. Would you have a recommendation to fix this?

Maybe the doc could be more specific about the `Int` range.

**Comment by legrostdg** [comment]
Wouldn't it be possible to use `Math.floor`?

    $ nodejs
    > Math.floor(2311048878.0)
    2311048878

**Comment by paulyoung** [comment]
I just ran into this and was confused because apparently the [integer range for numbers in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#Integer_range_for_Number) is bigger that `fromNumber` considers.

**Comment by hdgarrood** [comment]
This does come up fairly regularly so perhaps we should document it a bit more thoroughly. This is the intended behaviour and we are not considering changing it. The `Int` type is a normal twos-complement integer with a fixed number of bits (usually 32 or 64). It is not just a JavaScript number (ie, an IEEE 754 double) which happens to be an integer. There are a few reasons for this:

* Bitwise operations don't really make sense on doubles
* doubles have lots of strange behaviour which integers don't, for example you can have x+1==x with doubles. Proper 32- or 64-bit integers actually satisfy all of the ring axioms, which includes rules you would expect such as (x+y)+z==x+(y+z), whereas doubles barely satisfy any.
* defining the Int type as a double which happens to be an integer would put alternative backends into a really strange position where they'd have to basically replicate a quirk of JS (ie not having integers).

This is also why operations like x+y and x*y on Int get generated as x+y|0 in the JS. If you do want a double which happens to be integral there's a library for that: [Int53](
