### ISSUE TITLE
Add conversion to different base/radix?

### ISSUE THREAD

**Issue by sharkdp** [purescript/purescript-integers#17]
Currently, the purescript core libraries lack the possibility to convert integers between different bases.

As far as I can tell, the only related function is [`readInt`](https://pursuit.purescript.org/packages/purescript-globals/0.2.2/docs/Global#v:readInt) from purescript-globals with type signature:
``` purs
readInt :: Int -> String -> Number
```
This function is unsatisfactory for two reasons:
- it returns a `Number` (@hdgarrood explained to me, why this is the case: "you might want an integral value outside the 32 bit range")
- it can fail at runtime (returning `NaN`), see https://github.com/purescript/purescript-globals/issues/5.

In my opinion, the best option would be to add two functions to purescript-integers (in search for better names):
```purs
fromStringWithRadix :: Int -> String -> Maybe Int
toStringWithRadix :: Int -> Int -> String
```

The currently available `fromString` would become
``` purs
fromString :: String -> Maybe Int
fromString = fromStringWithRadix 10
```

I'd be happy to implement this, if you think this is a good idea.

**Comment by hdgarrood** [comment]
:+1: except I think I'd rather add Number versions somewhere else (Prelude? A purescript-numbers library?) and then just add versions here that wrap them. This way, people can still use them with larger integral Number values.

We might also consider making one of the arguments { radix :: Int }? That could increase readability and also prevent you from mixing them up accidentally.

**Comment by sharkdp** [comment]
> except I think I'd rather add Number versions somewhere else (Prelude? A purescript-numbers library?) and then just add versions here that wrap them. This way, people can still use them with larger integral Number values.

Agreed (this would also enable hex-floats, binary-floats... which I've never used before :smile:).

> We might also consider making one of the arguments { radix :: Int }? That could increase readability and also prevent you from mixing them up accidentally.

Do you mean a type synonym like:
``` purs
type Radix = Int
```

? (if yes, :+1:)

**Comment by hdgarrood** [comment]
No, I mean a record with a single "radix" field. Type synonyms make the docs easier to understand, but don't stop you from mixing the order up, whereas I think the record approach does both.

**Comment by garyb** [comment]
A `Radix` newtype would be a decent option for that too, and has zero runtime cost.

**Comment by sharkdp** [comment]
I've never seen this single-field-record trick, so I'd also go with the newtype solution.

Any thoughts on where to put the `Number` versions?
```purs
fromStringWithRadix :: Radix -> String -> Maybe Number
toStringWithRadix :: Radix -> Number -> String
```
(if they should really go into the Prelude, they definitely need other names)

As @hdgarrood suggests, the `Int`-versions could then be build via `fromNumber`/`toNumber`.

On the other hand, I would also be fine with just `Int` specific versions...

**Comment by texastoland** [comment]
I needed the `Number` version (works on floats) but don't have a good idea where to put it either.
