### ISSUE TITLE
Implementation of fromString

### ISSUE THREAD

**Issue by sharkdp** [purescript/purescript-integers#18]
I wanted to propose an implementation for #17 and noticed that `fromString` is currently implemented using `parseFloat`. Is there any reason that `parseFloat` is preferred over `parseInt` (which has a `radix` argument)?

The only reason I can see is that currently the tests require that:
``` purs
  log "fromString should fail to read floats"
  assert $ fromString "0.1" == Nothing
```
which seems reasonable. Naively switching to `parseInt` would result in the `0` getting parsed and the `.1` being ignored.

On the other hand, `parseFloat` also fails this requirement, if we do something like this:
``` purs
> fromString "42.000000000000001"
Just (42)
```
And `parseFloat` also ignores weird suffixes:
``` purs
> fromString "42,12"
Just (42)
```

**Comment by garyb** [comment]
Ugh, yeah I think the intention was that only actual integers would be parsed, but as you've illustrated that doesn't really work. I guess we need to examine the string to determine that instead.
