### ISSUE TITLE
Fix mod for negative numbers

### ISSUE THREAD

**Issue by jdegoes** [purescript/purescript-integers#2]
`mod -10 3` should be equal to `-1`, because:

`(-10 / 3)|0 = -3`

`-3 * 3 = -9`

And by law:

`-9 + (mod -10 3) = -10`

Therefore, `mod -10 3 = -1`.

**Comment by garyb** [comment]
This is actually the behaviour of the standard JS `%`, that makes it a nice easy fix!

**Comment by garyb** [comment]
Fixed in dc91a502c2a7278386c1a065bebd87d8db433a9c
