### ISSUE TITLE
fromNumberImpl does not work for very large ints

### ISSUE THREAD

**Issue by felixSchl** [purescript/purescript-integers#28]
https://github.com/purescript/purescript-integers/blob/4ef3a1e55de4be3cd8a48406956776a47aba0d73/src/Data/Int.js#L9

```
9114756780654345000 | 0 = -50578432
```

**Comment by felixSchl** [comment]
How about we use this suggested polyfill using `Math.floor`?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

```
return typeof value === 'number' && 
    isFinite(value) && 
    Math.floor(value) === value;
```

**Comment by hdgarrood** [comment]
I think this is working as it should - note that the `Int` type does not go larger than 2^31 - 1.

**Comment by felixSchl** [comment]
Ok, that's fair. I found this helpful to explain why: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by hdgarrood** [comment]
The `Int` type is more restricted than that - the bitwise operators which you get in the generated code for adding or multiplying `Int` values are there to ensure that they remain 32-bit integers, so that overflow is predictable and so that the bitwise operators behave as you'd expect them to.

**Comment by felixSchl** [comment]
Thanks for the explanation
