### ISSUE TITLE
define Data.Int.Long

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-integers#29]
When wrapping some existing JS APIs, or in general, we might want Integer numbers which might not necessarily be in range of 32 bit Integer (Data.Int), but have guaranty that they are Integer. example of this will be `Blob.prototype.slice` method which should take Integer as argument but using Int is not fine as it's too small. on the other hand using Number is not fine as only Integer values make sense https://github.com/purescript-web/purescript-dom/issues/125#issuecomment-332300207

So what you thing on defining `Data.Int.Long` (or different name) which will be like `Int` but instead of `(n | 0) === n` in `fromNumber` we use `Number.IsSafeInteger(n)` 

related to #28

**Comment by hdgarrood** [comment]
I think that already exists, in purescript-int-53?

**Comment by safareli** [comment]
Thanks! will use that

**Comment by jvliwanag** [comment]
Just in case someone needs a full 64 bit long, I've made one available [here](https://github.com/zapph/purescript-longs).
