### ISSUE TITLE
Precision and laws

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-integers#4]
Getting integers to behave acceptably in JavaScript is harder than it seemed at first, due to the underlying `Number` representation.

Because we're using `|0`, we're pretending `Int` is in the range of `Int32`. We currently don't apply `|0` to the result of multiplication so you can end up with numbers out of that range (so this should probably be considered a bug). If we do apply it to multiplication results, multiplication is no longer associative when a product overflows the `Int32` range.

Even if we don't use `|0`, there is still a problem here, as JavaScript still has an upper and lower bound on values that are safe to represent as integers, ±9007199254740991, and additionally, using `Math.floor` everywhere will be significantly slower than `|0`.

I suppose technically `Number` is not law abiding either due to precision and representation problems. Do we just have to accept that both these types aren't true `Semiring`s (etc)?

**Comment by jdegoes** [comment]
Number nor Int abide by any laws. In this case, I think it's better to pretend that they do, since arbitrary precision reals and integers are not all that practical for many applications.

**Comment by garyb** [comment]
Thanks for the input, that seems reasonable to me. We'll just have to stop `QuickCheck` and `StrongCheck` from generating `Int` values that are particularly large if we want their law checks to pass.
