### ISSUE TITLE
Port `Global.readInt` to this repo

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript-integers#42]
Originally [`readInt` was not going to be ported](https://github.com/purescript/purescript-numbers/pull/12#discussion_r521609397) from the deprecated `purescript-globals` repo. I've since learned that `purescript-uri` uses it in its implementation.

Is that a good enough reason to port this function here?

**Comment by hdgarrood** [comment]
Yes, I think so. Although can I suggest calling it `fromStringInBase` instead so that it’s clear that it’s a variant of `fromString`?

**Comment by JordanMartinez** [comment]
Works for me!

**Comment by JordanMartinez** [comment]
Turns out this function already exists as `fromStringAs (Radix baseValue)`. However, the implementations are not the same.
- [readInt FFI](https://github.com/purescript/purescript-globals/blob/master/src/Global.js#L12)
- [fromStringAs FFI](https://github.com/purescript/purescript-integers/blob/master/src/Data/Int.js#L16)

How should we resolve this situation. Should `readInt` still be ported from `Global` and renamed to `fromStringInBase`?

**Comment by hdgarrood** [comment]
I think if the function already exists here we shouldn’t need to add it again. It doesn’t particularly bother me that the implementations differ, although it might be worth testing that they behave the same for values within the Int range, just in case.

**Comment by hdgarrood** [comment]
Ah, I think I see what’s going on. The FFI implementation here delegates to `parseInt` which is what `Global.readInt` is based on anyway, but the function here also uses a regex to ensure that the _complete_ string parses; JavaScript’s `parseInt` will accept `"100 doo be doo"` and return `100` IIRC, which is widely considered to have been a mistake. Given this, I don’t see much value in providing a binding directly to `parseInt`.

**Comment by kl0tl** [comment]
Should we close this then?
