### ISSUE TITLE
building with bower / switching to spago 

### ISSUE THREAD

**Issue by joprice** [purescript/purescript-integers#43]
I'm trying to contribute to some tests in order to use this project to validate changes in purescript-native's ffi code (https://github.com/andyarvanitis/purescript-native-go-ffi/pull/16#issuecomment-742518591). I'm relatively new to purescript and only familiar with the spago workflow, and am having trouble building this project. I tried installing with bower, but building gives me errors like the following:

```
* Building project in /Users/josephprice/dev/purescript-integers
[1/24 ErrorParsingModule] bower_components/purescript-control/src/Data/Monoid/Alternate.purs:18:19

  18  newtype Alternate :: forall k. (k -> Type) -> k -> Type
                        ^^

  Unable to parse module:
  Unexpected token '::'

[2/24 ErrorParsingModule] bower_components/purescript-effect/src/Effect.purs:18:6

  18  type role Effect representational
           ^^^^

  Unable to parse module:
  Unexpected token 'role'

```

Is there something that needs to be updated to make this build, or can I help by submitting a pr to switch to spago?

**Comment by hdgarrood** [comment]
Switching to spago is not really an option right now, see https://github.com/purescript/purescript/issues/3942#issuecomment-741414900 for more details.

It looks to me like you're trying to build the library with an 0.13.x version of the compiler. In the `master` branch we no longer support 0.13.x, because we're preparing for the upcoming 0.14.0 compiler release. I'd suggest checking out the most recent tag instead, as that should build with 0.13.x compilers.

**Comment by joprice** [comment]
Ah, I see what's going on now. I'm pulling in purs 0.13 from my home-manager. I assumed that pulp managed the version of purs for you, but it's finding it from the path. I checked out v4.0.0 instead and after wiping out bower_components and node_modules, everything compiles but I get the following error when trying to run tests

```
> pulp test --check-main-type Effect.Effect

* Building project in /Users/josephprice/dev/purescript-integers
           Src   Lib   All
Warnings   0     0     0
Errors     0     0     0
* Build successful.
* Running tests...
* ERROR: Entry point module (Test.Main) not found.
```

**Comment by hdgarrood** [comment]
The `--check-main-type` option isn't supported any more, as that's something which really should always have been handled inside the compiler. I think if you update to the newest version of pulp and just run `pulp test` then that will fix that issue.

**Comment by joprice** [comment]
Nice that worked. Thank you for the help.
