### ISSUE TITLE
Why does the show instance for Int include "fromNumber"?

### ISSUE THREAD

**Issue by felixSchl** [purescript/purescript-integers#5]
This way, in order to convert to string, I need to apply `show <<< toNumber`. Is it unreasonable to expect the show instance to just return the number as a string?

**Comment by garyb** [comment]
There's an informal law that `Show` instances are supposed to return a value that is a valid PureScript representation of the value. Although I'm inclined to agree with you here, it is a bit irritating in this case. Maybe adding an explicit `intToString` would be an alternative.

**Comment by felixSchl** [comment]
I see what you mean, but `fromNumber` seems arbitrary to me because it is telling me not only what the value is, but also where it came from. It just happens to be the only way to get an Int at the moment, but if there was a `fromFoo`, then which do we choose? Maybe it could be "Int x"?

I think this law should be formalised or documented if this is a thing, because I remember in Haskell doing `read` and `show` on numbers is a legit way of converting between the two. I would have to confirm this for Haskell's `Int` or `Integers` but if my memory doesn't let me down, the same applied.

**Comment by garyb** [comment]
Well, even if there was a `fromFoo`, the canonical form would still be `fromNumber n`, as the `Int` will still contain a `Number` value, given that's what the parser interprets any numerical value as. The `Int` constructor will never be exposed directly, so `Int 0` wouldn't be executable code.

I'm not totally in favour of this situation though. I'd quite like something like Haskell's `OverloadedStrings`, but I think @paf31 would prefer to use templates.

The `Show` thing is documented actually https://github.com/purescript/purescript/blob/master/prelude/README.md#show :)

**Comment by garyb** [comment]
This won't be the case for much longer, so closing.
