### ISSUE TITLE
Declaration complement conflicts with import Data.Int.Bits

### ISSUE THREAD

**Issue by chutichhuy** [purescript/purescript-integers#7]
Hi,
I got this error message while trying to compile using the tool Pulp with Purescript version 0.7 RC1

```
Error:
Error in module Data.Int.Bits:
Declaration complement conflicts with import Data.Int.Bits
```
I'm new to Purescript, tried to have a look at the source but I didn't have any idea of what was the problem. 
Thanks

**Comment by paf31** [comment]
What is the output of `psc` with no arguments? It should be one line "// Generated by psc 0.7.0.0"

Also what does `ls bower_components` say?

**Comment by chutichhuy** [comment]
here is my bower_components 
```
purescript-arrays   purescript-functions  purescript-monoid
purescript-console  purescript-integers   purescript-prelude
purescript-control  purescript-invariant  purescript-st
purescript-eff      purescript-maybe
```
And psc 
```
Warning:
There is no Prelude module loaded, and the --no-prelude option was not specified.
You probably need to install the Prelude and other dependencies using Bower.
See https://github.com/purescript/purescript/wiki/Error-Code-PreludeNotPresent for more information, or to contribute content related to this error.

// Generated by psc version 0.7.0.0
```

**Comment by paf31** [comment]
Is this a new project? What version of `integers` do you have?

**Comment by chutichhuy** [comment]
It's new. Actually I was trying out the tool Pulp and compiling its skeleton code. Which is only a hello world kind of stuff.

```
module Main where

import Debug.Trace

main = do
  trace "Hello sailor!"

```

**Comment by paf31** [comment]
If you're new, I wouldn't use 0.7RC1 honestly. It's for development only right now, and the pulp tool almost certainly doesn't support it.

Maybe try starting with 0.6.9.5. When we release 0.7 (soon), I'll post a migration guide.

**Comment by chutichhuy** [comment]
Thanks,
I was moving to 0.7.0 because with 0.6.* I always got an error that stated that some Prelude modules has been defined multiple times, even when I used --no-prelude. I tried 0.7 because the release note said the Prelude is removed starting from this version, so I thought they are related somehow.

**Comment by paf31** [comment]
Sorry, you've picked a tricky week to start learning :) We're right in the middle of a new major version rollout, sorry.

See here:

https://github.com/purescript/purescript/wiki/Error-Code-RedefinedModule

The latest core libraries are for the new compiler, and don't work with `0.6.*`. Next week, everything should be ready, but until then you should make sure to only install versions prior to the current latest.

**Comment by chutichhuy** [comment]
thanks ;)
